name: tests
on: [push, pull_request]
jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-18.04
          - ubuntu-20.04
        python-version:
          - '2.7'
          - '3.9'
          - '3.10'
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (linux)
        if: runner.os == 'Linux'
        run: sudo apt install --yes libpoppler-cpp-dev pkg-config
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install pkg-config poppler
      - name: Test
        run: python setup.py test

  test_conda:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - ubuntu-20.04
          - windows-2022
    name: Conda on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: '3.10'
      - name: Configure conda
        shell: bash -l {0}
        run: conda config --remove channels defaults
      - name: Install dependencies
        shell: bash -l {0}
        run: conda install c-compiler cxx-compiler pkg-config poppler
      - name: Test
        shell: bash -l {0}
        run: python setup.py test
