name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - ubuntu-22.04
          - ubuntu-24.04
        python-version:
          - '3.13'
          - '3.14'
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt install --fix-missing --yes libpoppler-cpp-dev pkg-config
          pip install setuptools
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config poppler
          pip install setuptools
      - name: Install
        run: pip install --verbose --editable .
      - name: Test
        run: python -m unittest discover --verbose --start-directory tests
